[package]
version = "0.1.0"
name = "dcap-sp1-guest-program"
edition = "2021"

[dependencies]
core = { path = "../core" }
dcap-rs = { workspace = true }
sp1-zkvm = { workspace = true }
serde_json = { workspace = true }